version: '2'

services:
  # app server
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    hostname: app
    image: flask-full
    volumes:
      - .:/srv/flask-full
    command: ./docker/app/run_app.sh
    ports:
      - "8080:8080"
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    environment:
      redis_host: "redis"
      mongo_host: "mongo"

  # Celery beat
  beat:
    image: flask-full
    volumes:
      - .:/srv/flask-full
    command: ./docker/beat/run_beat.sh
    links:
      - redis
      - mongo
      - mail
    depends_on:
      - mongo
      - redis
      - mail
    environment:
      redis_host: "redis"
      mongo_host: "mongo"

  # Celery worker
  worker:
    image: flask-full
    volumes:
      - .:/srv/flask-full
    command: ./docker/worker/run_worker.sh
    links:
      - redis
      - mongo
      - mail
    depends_on:
      - redis
      - mongo
      - mail
    environment:
      redis_host: "redis"
      mongo_host: "mongo"
      mail_host: "mail"

  redis:
    image: redis:4.0.9
    hostname: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:3.6.4
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  mail:
    image: namshi/smtp
    hostname: mail
    ports:
      - "25:25"